package nz.coreyh.risktionary.ai.domain

/**
 * Represents the outcome of an AI model invocation.
 */
sealed interface AiResponse<out T> {
    /**
     * A successful AI response containing the deserialized data and detailed
     * token‑usage information reported by the model.
     *
     * @param data The typed response body returned by the AI model.
     * @param promptTokens Number of tokens consumed by the prompt.
     * @param completionTokens Number of tokens generated by the model.
     * @param totalTokens Total tokens used for the request.
     */
    data class Success<out T>(
        val data: T,
        val promptTokens: Int,
        val completionTokens: Int,
        val totalTokens: Int,
    ) : AiResponse<T> {
        fun costToString() =
            "promptTokens=$promptTokens, totalTokens=$totalTokens, completionTokens=$completionTokens, totalTokens=$totalTokens"
    }

    /**
     * Represents a failed AI invocation. Contains a human‑readable error
     * message and an optional underlying exception.
     *
     * @param message Description of the failure.
     * @param cause Optional throwable providing additional error context.
     */
    data class Failure(
        val message: String,
        val cause: Throwable? = null,
    ) : AiResponse<Nothing>
}
