package nz.coreyh.risktionary.shared.util.dataurl

import org.springframework.util.MimeType

data class DecodedDataUrl(
    val bytes: ByteArray,
    val mimeType: MimeType,
) {
    // generated by IntelliJ
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (other !is DecodedDataUrl) return false

        if (!bytes.contentEquals(other.bytes)) return false
        if (mimeType != other.mimeType) return false

        return true
    }

    // generated by IntelliJ
    override fun hashCode(): Int {
        var result = bytes.contentHashCode()
        result = 31 * result + mimeType.hashCode()
        return result
    }
}
