spring:
  config:
    import: optional:file:.prod.env[.properties]

server:
  forward-headers-strategy: framework

app:
  frontend-url: "https://risktionary.csse.canterbury.ac.nz"
  auth:
    cookie:
      path: "/"
      secure: true
      same-site: lax
      access-token-name: risktionary_at
      login-success-redirect-url-name: risktionary_lr