spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}

  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true

logging:
  level:
    nz.coreyh.risktionary: debug