package nz.coreyh.risktionary.feedback.domain.model.analysis

import kotlin.time.Instant

/**
 * A single drawing screenshot with the AI's interpretation of it.
 *
 * [capturedAt] is when the screenshot was received (not when the analysis
 * finished), and [elapsedMs] is the time since the round's drawing began, or
 * null if that is unknown.
 */
data class DrawingAnalysisEntry(
    val imageBytes: ByteArray,
    val mimeType: String,
    val result: DrawingAnalysisResult,
    val capturedAt: Instant,
    val elapsedMs: Long?,
) {
    // generated by IntelliJ
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (other !is DrawingAnalysisEntry) return false

        if (!imageBytes.contentEquals(other.imageBytes)) return false
        if (mimeType != other.mimeType) return false
        if (result != other.result) return false
        if (capturedAt != other.capturedAt) return false
        if (elapsedMs != other.elapsedMs) return false

        return true
    }

    // generated by IntelliJ
    override fun hashCode(): Int {
        var result1 = imageBytes.contentHashCode()
        result1 = 31 * result1 + mimeType.hashCode()
        result1 = 31 * result1 + result.hashCode()
        result1 = 31 * result1 + capturedAt.hashCode()
        result1 = 31 * result1 + (elapsedMs?.hashCode() ?: 0)
        return result1
    }
}
