package nz.coreyh.risktionary.feedback.domain.model.analysis

data class DrawingAnalysisEntry(
    val imageBytes: ByteArray,
    val result: DrawingAnalysisResult,
) {
    // generated by IntelliJ
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (other !is DrawingAnalysisEntry) return false

        if (!imageBytes.contentEquals(other.imageBytes)) return false
        if (result != other.result) return false

        return true
    }

    // generated by IntelliJ
    override fun hashCode(): Int {
        var result1 = imageBytes.contentHashCode()
        result1 = 31 * result1 + result.hashCode()
        return result1
    }
}
